builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - 386
checksum:
  name_template: 'checksums-linux.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
