name: CI
on: [push]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
      env:
        GO111MODULE: on

    - name: Run lint
      run: |
        go get -u golang.org/x/lint/golint
        $(go env GOPATH)/bin/golint -set_exit_status
      env:
        GO111MODULE: on

    - name: Run golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8
        $(go env GOPATH)/bin/golangci-lint run --disable errcheck
      env:
        GO111MODULE: on

    - name: Run test
      run: |
        go test -v
      env:
        GO111MODULE: on
