on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release(Windows)

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:

      - name: Install goreleaser
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          iwr -useb get.scoop.sh | iex
          scoop bucket add goreleaser https://github.com/goreleaser/scoop-bucket.git
          scoop install goreleaser

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run release
        run: |
          goreleaser.exe release --rm-dist -f .goreleaser-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
