name: Release
on: [push]

# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  base:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

  linux:
    runs-on: ubuntu-latest
    needs: [base]
    steps:
      - name: Install goreleaser
        run: |
          sudo snap install --classic goreleaser

      - name: Run release
        run: |
          goreleaser release --rm-dist -f .goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  darwin:
    runs-on: macos-latest
    needs: [base]
    steps:
      - name: Install goreleaser
        run: |
          brew install goreleaser/tap/goreleaser

      - name: Run release
        run: |
          goreleaser release --rm-dist -f .goreleaser-darwin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  windows:
    runs-on: windows-latest
    needs: [base]
    steps:
      - name: Install goreleaser
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          iwr -useb get.scoop.sh | iex
          scoop bucket add goreleaser https://github.com/goreleaser/scoop-bucket.git
          scoop install goreleaser

      - name: Run release
        run: |
          C:\Users\runneradmin\scoop\shims\goreleaser.exe release --rm-dist -f .goreleaser-windows.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
